timeout: 30   # the qemu testing can take some time
email:
  users: 'ci-notifications@foundries.io'
triggers:
  - name: upstream-merge
    type: git_poller
    params:
      GIT_URL: https://github.com/zephyrproject-rtos/zephyr.git
      GIT_POLL_REFS: "refs/heads/master"
    runs:
      #- name: sanity-nrf52
      #  container: zephyrprojectrtos/zephyr-build
      #  host-tag: zephyr-nrf52
      #  privileged: true
      #  params:
      #    PLATFORM: nrf52_blenano2
      #    PYOCD_BOARD_NAME: RedBearLab-BLE-Nano2
      #    FLAKY_TESTS: |
      #      tests/kernel/interrupt
      #  script-repo:
      #    name: fio
      #    path: zephyr/sanity.sh

      - name: sanity-qemu-{loop}
        container: zephyrprojectrtos/zephyr-build
        host-tag: amd64
        script-repo:
          name: fio
          path: zephyr/sanity.sh
        loop-on:
          - param: PLATFORM
            values: [frdm_k64f, reel_board, nrf52840_pca10056]
        params:
          FLAKY_TESTS: |
            kernel/init
            kernel/sched/schedule_api
            kernel/timer/timer_api
            kernel/timer/timer_monotonic
            cmsis_rtos_v1

      - name: zephyr-sample-mcumgr-{loop}
        container: zephyrprojectrtos/zephyr-build
        host-tag: amd64
        script-repo:
          name: fio
          path: zephyr/sample.sh
        params:
            APP: samples/subsys/mgmt/mcumgr/smp_svr/
        loop-on:
          - param: PLATFORM
            values: [reel_board, nrf52840_pca10056]

params:
  archive: /archive

script-repos:
  fio:
    clone-url: https://github.com/foundriesio/ci-scripts
