timeout: 60   # the qemu testing can take some time
email:
  users: 'mike@foundries.io'
triggers:
  - name: fio-pull-request
    type: github_pr
    runs:
      - name: sanity-compile-nrf52840_pca10056
        container: zephyrprojectrtos/zephyr-build
        container-user: root
        container-entrypoint: ""
        host-tag: amd64
        triggers:
          - name: sanity-test
        params:
          SAVE_OUTDIR: "1"
          PLATFORM: nrf52840_pca10056
        script-repo:
          name: fio
          path: zephyr/sanity-compile.sh

  - name: upstream-merge
    type: git_poller
    params:
      GIT_URL: https://github.com/zephyrproject-rtos/zephyr.git
      GIT_POLL_REFS: "refs/heads/master"
    runs:
      - name: sanity-compile-nrf52840_pca10056
        container: zephyrprojectrtos/zephyr-build
        container-user: root
        container-entrypoint: ""
        host-tag: amd64
        triggers:
          - name: sanity-test
        params:
          SAVE_OUTDIR: "1"
          PLATFORM: nrf52840_pca10056
        script-repo:
          name: fio
          path: zephyr/sanity-compile.sh

      - name: sanity-compile-{loop}
        container: zephyrprojectrtos/zephyr-build
        container-user: root
        container-entrypoint: ""
        host-tag: amd64
        script-repo:
          name: fio
          path: zephyr/sanity-compile.sh
        loop-on:
          - param: PLATFORM
            values: [frdm_k64f, reel_board, nrf52_blenano2]

      - name: zephyr-sample-mcumgr-{loop}
        container: zephyrprojectrtos/zephyr-build
        container-user: root
        container-entrypoint: ""
        host-tag: amd64
        script-repo:
          name: fio
          path: zephyr/sample.sh
        params:
            APP: samples/subsys/mgmt/mcumgr/smp_svr/
        loop-on:
          - param: PLATFORM
            values: [reel_board, nrf52840_pca10056]

  - name: sanity-test
    type: simple
    runs:
      - name: sanity-test-nrf52840_pca10056
        container: zephyrprojectrtos/zephyr-build
        container-user: root
        container-entrypoint: ""
        host-tag: zephyr-nrf52840-pca10056
        privileged: true
        params:
          PYOCD_BOARD_NAME: nRF52840-DK
        script-repo:
          name: fio
          path: zephyr/sanity-device.sh


params:
  archive: /archive
  FLAKY_TESTS: |
    samples/display/ili9340
    samples/drivers/led_lp5562
    samples/gui/lvgl
    samples/subsys/usb/cdc_acm
    samples/subsys/usb/cdc_acm_composite
    samples/subsys/usb/console
    samples/subsys/usb/dfu
    samples/subsys/usb/testusb
    tests/benchmarks/sched
    tests/drivers/counter/counter_basic_api
    tests/drivers/pwm/pwm_api
    tests/kernel/interrupt
    tests/kernel/sched/schedule_api
    tests/kernel/mem_slab/mslab_threadsafe
    tests/net/ieee802154/fragment
    tests/subsys/fs/littlefs
    tests/subsys/fs/nffs_fs_api/cache
    tests/subsys/fs/nffs_fs_api/large
    tests/subsys/usb/desc_sections
    tests/subsys/usb/device


script-repos:
  fio:
    clone-url: https://github.com/foundriesio/ci-scripts
